name: flutter_asset_chart
description: A sample project showing how to create a chart from a Rest API
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.0.1
  json_serializable: ^6.1.5
  json_annotation: ^4.4.0
  fl_chart: ^0.50.1
  freezed: ^1.1.1
  injectable: ^1.5.3
  get_it: ^7.2.0
  dio: ^4.0.6
  flutter_svg: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.8
  injectable_generator: ^1.5.3

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_intl:
  enabled: true
